### ISSUE TITLE
lit-html 1.2.0 Release Plan

### ISSUE THREAD

**Issue by nicolejadeyee** [Polymer/lit-html#1084]
# 1.2.0 Release Plan

Release Plan that outlines the focused tasks for lit-html 1.2.0.

[Milestone](https://github.com/Polymer/lit-html/milestone/14)

## Notable Changes
- Enhancements
  - [x] [Add templateContent() directive](https://github.com/Polymer/lit-html/pull/1058)
  - [x] [Add unsafeSVG for rendering SVG snippets](https://github.com/Polymer/lit-html/pull/1000)
  - [x] [Add live() directive](https://github.com/Polymer/lit-html/pull/1057)
  - [x] [Add sanitization system for preventing XSS attacks](https://github.com/Polymer/lit-html/pull/1031)
- Bug Fixes
  - [x] [classMap directive does not work with SVG](https://github.com/Polymer/lit-html/pull/1070)
  - [x] [Support namespaced attributes](https://github.com/Polymer/lit-html/issues/423)
- Infrastructure
  - [x] [Port docs site to eleventy](https://github.com/Polymer/lit-html/pull/1076)
  - [x] [Long Build Time for Docs](https://github.com/Polymer/lit-html/issues/1049)

## Documentation
- [x] [Document live() directive](https://github.com/Polymer/lit-html/issues/1063)
- [x] [Document templateContent() directive](https://github.com/Polymer/lit-html/issues/1067)
- [x] [Document unsafeSVG() directive](https://github.com/Polymer/lit-html/issues/1068)

## Release Process
- [x] [Run Google Internal Tests](https://github.com/Polymer/lit-html/issues/1085)
- [x] [1.2.0 Release Notes](https://github.com/Polymer/lit-html/issues/1086)
- [x] [Verify 1.2.0 CHANGELOG](https://github.com/Polymer/lit-html/issues/1087)
- [ ] [Prelease](https://github.com/Polymer/lit-html/issues/1115)

**Comment by csvn** [comment]
@nicolejadeyee All the PRs/issues in "infrastructure" and "Documentation" have been merged/closed. I guess the next step is the internal google tests?

**Comment by kevinmpowell** [comment]
Would it be possible to get a 1.2.0-alpha build deployed to npm? I'd really like to use `unsafeSVG` in a project I'm working on, but I need to alias `lit-html` when I install it so it doesn't collide with my lit-element dependency. I can only npm alias with registry packages, I can't alias a repo pointer.

I can fork and publish something myself, but I thought I'd ask.

**Comment by justinfagnani** [comment]
@kevinmpowell Sorry I didn't get back to you. We published 1.2.0 yesterday.
